-- Run once in the Supabase SQL editor.
-- Replace the example email at the bottom with the ONE Supabase Auth email allowed to publish.
create table if not exists public.admin_accounts (email text primary key check (email = lower(email)));
alter table public.admin_accounts enable row level security;

create or replace function public.is_safemind_admin() returns boolean language sql stable security definer set search_path = public as $$
select exists (select 1 from public.admin_accounts where email = lower(coalesce(auth.jwt() ->> 'email', '')));
$$;
revoke all on function public.is_safemind_admin() from public;
grant execute on function public.is_safemind_admin() to authenticated;
create table if not exists public.scam_education (
    id bigint generated by default as identity primary key,
    author_id uuid not null references auth.users(id) on delete cascade,
    title text not null check (char_length(title) between 1 and 140),
    category text not null check (char_length(category) between 1 and 60),
    content text not null check (char_length(content) between 1 and 10000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.scam_education enable row level security;

drop policy if exists "everyone reads scam education" on public.scam_education;
create policy "everyone reads scam education"
on public.scam_education for select to anon, authenticated
using (true);

drop policy if exists "admins publish scam education" on public.scam_education;
create policy "admins publish scam education"
on public.scam_education for insert to authenticated
with check (
    auth.uid() = author_id
    and public.is_safemind_admin()
);

drop policy if exists "admins update scam education" on public.scam_education;
create policy "admins update scam education"
on public.scam_education for update to authenticated
using (public.is_safemind_admin()) with check (public.is_safemind_admin());

drop policy if exists "admins delete scam education" on public.scam_education;
create policy "admins delete scam education"
on public.scam_education for delete to authenticated
using (public.is_safemind_admin());

-- IMPORTANT: change this to your real admin's Supabase Auth email.
insert into public.admin_accounts (email) values ('your-admin-email@example.com') on conflict (email) do nothing;
