-- SafeMind complete Supabase setup
-- Run this entire file once in Supabase Dashboard > SQL Editor.
-- It is idempotent and can be run again after application updates.

-- 1. Administrators ---------------------------------------------------------
create table if not exists public.admin_accounts (
    email text primary key check (email = lower(email))
);
alter table public.admin_accounts enable row level security;

create or replace function public.is_safemind_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select exists (
        select 1
        from public.admin_accounts
        where email = lower(coalesce(auth.jwt() ->> 'email', ''))
    );
$$;
revoke all on function public.is_safemind_admin() from public;
grant execute on function public.is_safemind_admin() to authenticated;

-- Add an administrator only after that email has a Supabase Auth account:
-- insert into public.admin_accounts (email)
-- values ('admin@example.com')
-- on conflict (email) do nothing;

-- 2. Manual reports and private screenshots --------------------------------
create table if not exists public.admin_reports (
    id bigint generated by default as identity primary key,
    reporter_id uuid not null references auth.users(id) on delete cascade,
    report_type text not null,
    content text not null,
    notes text,
    automated_result jsonb,
    screenshot_path text,
    screenshot_name text,
    screenshot_type text,
    screenshot_size bigint,
    status text not null default 'pending',
    created_at timestamptz not null default now()
);
alter table public.admin_reports add column if not exists screenshot_path text;
alter table public.admin_reports add column if not exists screenshot_name text;
alter table public.admin_reports add column if not exists screenshot_type text;
alter table public.admin_reports add column if not exists screenshot_size bigint;
alter table public.admin_reports enable row level security;

alter table public.admin_reports drop constraint if exists admin_reports_report_type_check;
alter table public.admin_reports add constraint admin_reports_report_type_check
check (report_type in ('message', 'link', 'phone', 'email', 'other'));
alter table public.admin_reports drop constraint if exists admin_reports_content_check;
alter table public.admin_reports add constraint admin_reports_content_check
check (char_length(content) between 1 and 5000);
alter table public.admin_reports drop constraint if exists admin_reports_notes_check;
alter table public.admin_reports add constraint admin_reports_notes_check
check (notes is null or char_length(notes) <= 2000);
alter table public.admin_reports drop constraint if exists admin_reports_automated_result_check;
alter table public.admin_reports add constraint admin_reports_automated_result_check
check (automated_result is null or octet_length(automated_result::text) <= 10000);
alter table public.admin_reports drop constraint if exists admin_reports_status_check;
alter table public.admin_reports add constraint admin_reports_status_check
check (status in ('pending', 'reviewing', 'confirmed', 'dismissed'));
alter table public.admin_reports drop constraint if exists admin_reports_screenshot_check;
alter table public.admin_reports add constraint admin_reports_screenshot_check check (
    (screenshot_path is null and screenshot_name is null and screenshot_type is null and screenshot_size is null)
    or (
        char_length(screenshot_path) between 38 and 200
        and char_length(screenshot_name) between 1 and 255
        and screenshot_type in ('image/png', 'image/jpeg', 'image/webp')
        and screenshot_size between 1 and 5242880
    )
);
create index if not exists admin_reports_reporter_created_idx
on public.admin_reports (reporter_id, created_at desc);
create index if not exists admin_reports_status_created_idx
on public.admin_reports (status, created_at desc);

drop policy if exists "users submit their own reports" on public.admin_reports;
create policy "users submit their own reports"
on public.admin_reports for insert to authenticated
with check (
    auth.uid() = reporter_id
    and status = 'pending'
    and (screenshot_path is null or split_part(screenshot_path, '/', 1) = auth.uid()::text)
);
drop policy if exists "users read their own reports" on public.admin_reports;
create policy "users read their own reports"
on public.admin_reports for select to authenticated
using (auth.uid() = reporter_id);
drop policy if exists "admins read all reports" on public.admin_reports;
create policy "admins read all reports"
on public.admin_reports for select to authenticated
using (public.is_safemind_admin());
drop policy if exists "admins update reports" on public.admin_reports;
create policy "admins update reports"
on public.admin_reports for update to authenticated
using (public.is_safemind_admin())
with check (public.is_safemind_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'report-screenshots',
    'report-screenshots',
    false,
    5242880,
    array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "users upload their report screenshots" on storage.objects;
create policy "users upload their report screenshots"
on storage.objects for insert to authenticated
with check (
    bucket_id = 'report-screenshots'
    and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "users read their report screenshots" on storage.objects;
create policy "users read their report screenshots"
on storage.objects for select to authenticated
using (
    bucket_id = 'report-screenshots'
    and (storage.foldername(name))[1] = auth.uid()::text
);
drop policy if exists "users delete their report screenshots" on storage.objects;
create policy "users delete their report screenshots"
on storage.objects for delete to authenticated
using (
    bucket_id = 'report-screenshots'
    and (storage.foldername(name))[1] = auth.uid()::text
    and not exists (
        select 1 from public.admin_reports
        where screenshot_path = name
    )
);
drop policy if exists "admins read report screenshots" on storage.objects;
create policy "admins read report screenshots"
on storage.objects for select to authenticated
using (bucket_id = 'report-screenshots' and public.is_safemind_admin());

-- 3. Scam education ---------------------------------------------------------
create table if not exists public.scam_education (
    id bigint generated by default as identity primary key,
    author_id uuid not null references auth.users(id) on delete cascade,
    title text not null check (char_length(title) between 1 and 140),
    category text not null check (char_length(category) between 1 and 60),
    content text not null check (char_length(content) between 1 and 10000),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.scam_education enable row level security;
drop policy if exists "everyone reads scam education" on public.scam_education;
create policy "everyone reads scam education"
on public.scam_education for select to anon, authenticated using (true);
drop policy if exists "admins publish scam education" on public.scam_education;
create policy "admins publish scam education"
on public.scam_education for insert to authenticated
with check (auth.uid() = author_id and public.is_safemind_admin());
drop policy if exists "admins update scam education" on public.scam_education;
create policy "admins update scam education"
on public.scam_education for update to authenticated
using (public.is_safemind_admin()) with check (public.is_safemind_admin());
drop policy if exists "admins delete scam education" on public.scam_education;
create policy "admins delete scam education"
on public.scam_education for delete to authenticated
using (public.is_safemind_admin());

-- 4. User scan credits and history -----------------------------------------
create table if not exists public.user_scan_progress (
    user_id uuid primary key references auth.users(id) on delete cascade,
    credits integer not null default 0,
    total_scans integer not null default 0,
    current_streak integer not null default 0,
    last_scan_date date,
    updated_at timestamptz not null default now()
);
create table if not exists public.user_scan_history (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    scan_type text not null check (scan_type in ('message', 'link', 'phone', 'email')),
    risk text not null check (risk in ('low', 'medium', 'high')),
    credits_earned integer not null default 10,
    created_at timestamptz not null default now()
);
alter table public.user_scan_progress enable row level security;
alter table public.user_scan_history enable row level security;
drop policy if exists "users read their progress" on public.user_scan_progress;
create policy "users read their progress"
on public.user_scan_progress for select to authenticated using (auth.uid() = user_id);
drop policy if exists "users read their scan history" on public.user_scan_history;
create policy "users read their scan history"
on public.user_scan_history for select to authenticated using (auth.uid() = user_id);

create or replace function public.award_scan_credit(scan_kind text, scan_risk text)
returns table (credits integer, total_scans integer, current_streak integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    today date := current_date;
begin
    if auth.uid() is null
       or scan_kind not in ('message', 'link', 'phone', 'email')
       or scan_risk not in ('low', 'medium', 'high') then
        raise exception 'Invalid scan';
    end if;
    if exists (
        select 1 from public.user_scan_history
        where user_id = auth.uid() and created_at > now() - interval '5 seconds'
    ) then
        return query
        select p.credits, p.total_scans, p.current_streak
        from public.user_scan_progress p where p.user_id = auth.uid();
        return;
    end if;
    insert into public.user_scan_history (user_id, scan_type, risk)
    values (auth.uid(), scan_kind, scan_risk);
    insert into public.user_scan_progress
        (user_id, credits, total_scans, current_streak, last_scan_date)
    values (auth.uid(), 10, 1, 1, today)
    on conflict (user_id) do update set
        credits = user_scan_progress.credits + 10,
        total_scans = user_scan_progress.total_scans + 1,
        current_streak = case
            when user_scan_progress.last_scan_date = today then user_scan_progress.current_streak
            when user_scan_progress.last_scan_date = today - 1 then user_scan_progress.current_streak + 1
            else 1
        end,
        last_scan_date = today,
        updated_at = now();
    return query
    select p.credits, p.total_scans, p.current_streak
    from public.user_scan_progress p where p.user_id = auth.uid();
end;
$$;
revoke all on function public.award_scan_credit(text, text) from public;
grant execute on function public.award_scan_credit(text, text) to authenticated;

-- 5. Verified threat directory ---------------------------------------------
create table if not exists public.threat_directory (
    id bigint generated by default as identity primary key,
    entry_type text not null check (entry_type in ('phone', 'message', 'link', 'email')),
    normalized_value text not null,
    verdict text not null check (verdict in ('scam', 'safe')),
    organization text,
    reason text not null,
    source_url text,
    created_at timestamptz not null default now(),
    unique (entry_type, normalized_value)
);
create table if not exists public.verified_organization_emails (
    id bigint generated by default as identity primary key,
    organization text not null,
    email text not null unique,
    purpose text not null,
    source_url text not null,
    verified_at timestamptz not null default now()
);
alter table public.threat_directory enable row level security;
alter table public.verified_organization_emails enable row level security;
drop policy if exists "public reads threat directory" on public.threat_directory;
create policy "public reads threat directory"
on public.threat_directory for select to anon, authenticated using (true);
drop policy if exists "public reads verified contacts" on public.verified_organization_emails;
create policy "public reads verified contacts"
on public.verified_organization_emails for select to anon, authenticated using (true);

-- Keep write access to verified records in the Supabase dashboard or a trusted
-- server. Never put the service-role key in this browser application.

-- 6. Agent observability ----------------------------------------------------
create table if not exists public.agent_runs (
    run_id uuid primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    intent text not null check (char_length(intent) between 1 and 80),
    intent_confidence numeric(5,4) not null check (intent_confidence between 0 and 1),
    parameters jsonb not null check (octet_length(parameters::text) <= 4000),
    selected_tools text[] not null default '{}',
    tool_selection_correct boolean,
    task_succeeded boolean not null,
    turns_to_completion smallint not null check (turns_to_completion between 1 and 100),
    feedback text check (feedback is null or feedback in ('confirm', 'cancel')),
    feedback_at timestamptz,
    estimated_cost_usd numeric(14,8) not null default 0 check (estimated_cost_usd >= 0),
    cache_hit boolean not null default false,
    latency_ms numeric(14,3) not null check (latency_ms >= 0),
    ttft_ms numeric(14,3) check (ttft_ms is null or ttft_ms >= 0),
    ttft_mode text,
    output_tokens_estimated integer check (output_tokens_estimated is null or output_tokens_estimated >= 0),
    tokens_per_second_estimated numeric(14,2) check (tokens_per_second_estimated is null or tokens_per_second_estimated >= 0),
    compute_device text not null default 'cpu',
    throughput_per_gpu numeric(14,2) check (throughput_per_gpu is null or throughput_per_gpu >= 0),
    batch_size integer not null default 1 check (batch_size > 0),
    batch_efficiency numeric(6,4) check (batch_efficiency is null or batch_efficiency between 0 and 1),
    created_at timestamptz not null default now()
);
create index if not exists agent_runs_created_idx on public.agent_runs (created_at desc);
create index if not exists agent_runs_user_created_idx on public.agent_runs (user_id, created_at desc);
alter table public.agent_runs enable row level security;
drop policy if exists "users insert their agent runs" on public.agent_runs;
create policy "users insert their agent runs" on public.agent_runs for insert to authenticated
with check (auth.uid() = user_id and coalesce((parameters ->> 'content_stored')::boolean, false) = false);
drop policy if exists "users read their agent runs" on public.agent_runs;
create policy "users read their agent runs" on public.agent_runs for select to authenticated
using (auth.uid() = user_id);
drop policy if exists "admins read all agent runs" on public.agent_runs;
create policy "admins read all agent runs" on public.agent_runs for select to authenticated
using (public.is_safemind_admin());
create or replace function public.submit_agent_feedback(target_run_id uuid, decision text)
returns boolean language plpgsql security definer set search_path = public, pg_temp as $$
begin
    if auth.uid() is null or decision not in ('confirm', 'cancel') then raise exception 'Invalid feedback'; end if;
    update public.agent_runs set feedback = decision, feedback_at = now()
    where run_id = target_run_id and user_id = auth.uid();
    return found;
end;
$$;
revoke all on function public.submit_agent_feedback(uuid, text) from public;
grant execute on function public.submit_agent_feedback(uuid, text) to authenticated;

-- 7. Investigation case files and vector-ready stores ----------------------
-- Run supabase-security-cases.sql after this file to enable case persistence,
-- continuous-learning labels, pgvector case embeddings, and RAG documents.
