-- Run this once in the Supabase SQL editor.
create table if not exists public.admin_reports (
    id bigint generated by default as identity primary key,
    reporter_id uuid not null references auth.users(id) on delete cascade,
    report_type text not null check (report_type in ('message', 'link', 'phone', 'email', 'other')),
    content text not null check (char_length(content) between 1 and 5000),
    notes text check (char_length(notes) <= 2000),
    automated_result jsonb check (automated_result is null or octet_length(automated_result::text) <= 10000),
    screenshot_path text,
    screenshot_name text,
    screenshot_type text,
    screenshot_size bigint,
    status text not null default 'pending' check (status in ('pending', 'reviewing', 'confirmed', 'dismissed')),
    created_at timestamptz not null default now()
);

alter table public.admin_reports enable row level security;

alter table public.admin_reports add column if not exists screenshot_path text;
alter table public.admin_reports add column if not exists screenshot_name text;
alter table public.admin_reports add column if not exists screenshot_type text;
alter table public.admin_reports add column if not exists screenshot_size bigint;

alter table public.admin_reports drop constraint if exists admin_reports_screenshot_check;
alter table public.admin_reports add constraint admin_reports_screenshot_check check (
    (screenshot_path is null and screenshot_name is null and screenshot_type is null and screenshot_size is null)
    or (
        char_length(screenshot_path) between 38 and 200
        and char_length(screenshot_name) between 1 and 255
        and screenshot_type in ('image/png', 'image/jpeg', 'image/webp')
        and screenshot_size between 1 and 5242880
    )
);

-- Upgrade installations created before email scanning was added.
alter table public.admin_reports drop constraint if exists admin_reports_report_type_check;
alter table public.admin_reports add constraint admin_reports_report_type_check
check (report_type in ('message', 'link', 'phone', 'email', 'other'));

drop policy if exists "users submit their own reports" on public.admin_reports;
create policy "users submit their own reports"
on public.admin_reports for insert to authenticated
with check (
    auth.uid() = reporter_id
    and status = 'pending'
    and (screenshot_path is null or split_part(screenshot_path, '/', 1) = auth.uid()::text)
);

drop policy if exists "users read their own reports" on public.admin_reports;
create policy "users read their own reports"
on public.admin_reports for select to authenticated
using (auth.uid() = reporter_id);

drop policy if exists "admins read all reports" on public.admin_reports;
create policy "admins read all reports"
on public.admin_reports for select to authenticated
using (public.is_safemind_admin());

drop policy if exists "admins update reports" on public.admin_reports;
create policy "admins update reports"
on public.admin_reports for update to authenticated
using (public.is_safemind_admin())
with check (public.is_safemind_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'report-screenshots',
    'report-screenshots',
    false,
    5242880,
    array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "users upload their report screenshots" on storage.objects;
create policy "users upload their report screenshots"
on storage.objects for insert to authenticated
with check (
    bucket_id = 'report-screenshots'
    and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "users read their report screenshots" on storage.objects;
create policy "users read their report screenshots"
on storage.objects for select to authenticated
using (
    bucket_id = 'report-screenshots'
    and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "users delete their report screenshots" on storage.objects;
create policy "users delete their report screenshots"
on storage.objects for delete to authenticated
using (
    bucket_id = 'report-screenshots'
    and (storage.foldername(name))[1] = auth.uid()::text
    and not exists (
        select 1 from public.admin_reports
        where screenshot_path = name
    )
);

drop policy if exists "admins read report screenshots" on storage.objects;
create policy "admins read report screenshots"
on storage.objects for select to authenticated
using (bucket_id = 'report-screenshots' and public.is_safemind_admin());
