-- Run once in the Supabase SQL editor after reviewing the demo seed records.
create table if not exists public.threat_directory (
    id bigint generated by default as identity primary key,
    entry_type text not null check (entry_type in ('phone','message','link','email')),
    normalized_value text not null,
    verdict text not null check (verdict in ('scam','safe')),
    organization text,
    reason text not null,
    source_url text,
    created_at timestamptz not null default now(),
    unique(entry_type, normalized_value)
);

create table if not exists public.verified_organization_emails (
    id bigint generated by default as identity primary key,
    organization text not null,
    email text not null unique,
    purpose text not null,
    source_url text not null,
    verified_at timestamptz not null default now()
);

alter table public.threat_directory enable row level security;
alter table public.verified_organization_emails enable row level security;

drop policy if exists "public reads threat directory" on public.threat_directory;
create policy "public reads threat directory" on public.threat_directory for select to anon, authenticated using (true);
drop policy if exists "public reads verified contacts" on public.verified_organization_emails;
create policy "public reads verified contacts" on public.verified_organization_emails for select to anon, authenticated using (true);

insert into public.verified_organization_emails (organization,email,purpose,source_url) values
('Microsoft','phish@office365.microsoft.com','Phishing reports','https://support.microsoft.com/en-us/security/protect-yourself-from-phishing'),
('PayPal','phishing@paypal.com','Suspicious email and text reports','https://www.paypal.com/us/security/report-suspicious-messages'),
('Apple','reportphishing@apple.com','Phishing reports','https://support.apple.com/en-us/102406'),
('Amazon','stop-spoofing@amazon.com','Suspicious email reports','https://aws.amazon.com/security/report-suspicious-emails/')
on conflict (email) do update set purpose=excluded.purpose, source_url=excluded.source_url, verified_at=now();

-- Hackathon demonstration records. These clearly reserved/example values are
-- not claims about real people, phone numbers, or live websites.
insert into public.threat_directory (entry_type,normalized_value,verdict,organization,reason,source_url) values
('phone','+19005550100','scam',null,'Hackathon demonstration scam number',null),
('phone','+12025550147','safe',null,'Hackathon demonstration safe number',null),
('message','your account will close today unless you verify now','scam',null,'Urgency and account-verification phishing pattern',null),
('message','your requested monthly statement is ready in the official app','safe',null,'Hackathon demonstration safe notification',null),
('link','https://secure-login.example.com/verify','scam',null,'Reserved example domain with phishing-style login path',null),
('link','https://www.microsoft.com','safe','Microsoft','Official Microsoft web domain','https://www.microsoft.com/'),
('email','microsoft-support@outlook-security.example','scam',null,'Reserved example sender impersonating Microsoft',null),
('email','phishing@paypal.com','safe','PayPal','Official PayPal phishing-report address','https://www.paypal.com/us/security/report-suspicious-messages')
on conflict (entry_type,normalized_value) do update set verdict=excluded.verdict,organization=excluded.organization,reason=excluded.reason,source_url=excluded.source_url;

-- Do not grant insert/update/delete access to browser users. Maintain verified
-- records through the Supabase dashboard or a trusted server only.
