-- Run once in Supabase SQL editor to enable scan credits and streaks.
create table if not exists public.user_scan_progress (
 user_id uuid primary key references auth.users(id) on delete cascade,
 credits integer not null default 0, total_scans integer not null default 0,
 current_streak integer not null default 0, last_scan_date date, updated_at timestamptz not null default now()
);
create table if not exists public.user_scan_history (
 id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade,
 scan_type text not null check (scan_type in ('message','link','phone','email')),
 risk text not null check (risk in ('low','medium','high')), credits_earned integer not null default 10,
 created_at timestamptz not null default now()
);
alter table public.user_scan_progress enable row level security;
alter table public.user_scan_history enable row level security;
drop policy if exists "users read their progress" on public.user_scan_progress;
create policy "users read their progress" on public.user_scan_progress for select to authenticated using (auth.uid()=user_id);
drop policy if exists "users read their scan history" on public.user_scan_history;
create policy "users read their scan history" on public.user_scan_history for select to authenticated using (auth.uid()=user_id);

create or replace function public.award_scan_credit(scan_kind text, scan_risk text)
returns table (credits integer,total_scans integer,current_streak integer)
language plpgsql security definer set search_path=public as $$
declare today date:=current_date;
begin
 if auth.uid() is null or scan_kind not in ('message','link','phone','email') or scan_risk not in ('low','medium','high') then raise exception 'Invalid scan'; end if;
 if exists (select 1 from public.user_scan_history where user_id=auth.uid() and created_at > now()-interval '5 seconds') then
  return query select p.credits,p.total_scans,p.current_streak from public.user_scan_progress p where p.user_id=auth.uid();
  return;
 end if;
 insert into public.user_scan_history(user_id,scan_type,risk) values(auth.uid(),scan_kind,scan_risk);
 insert into public.user_scan_progress(user_id,credits,total_scans,current_streak,last_scan_date) values(auth.uid(),10,1,1,today)
 on conflict(user_id) do update set credits=user_scan_progress.credits+10,total_scans=user_scan_progress.total_scans+1,
 current_streak=case when user_scan_progress.last_scan_date=today then user_scan_progress.current_streak when user_scan_progress.last_scan_date=today-1 then user_scan_progress.current_streak+1 else 1 end,
 last_scan_date=today,updated_at=now();
 return query select p.credits,p.total_scans,p.current_streak from public.user_scan_progress p where p.user_id=auth.uid();
end; $$;
revoke all on function public.award_scan_credit(text,text) from public;
grant execute on function public.award_scan_credit(text,text) to authenticated;
